### ISSUE TITLE
encodingPlugin is not defined webpack

### ISSUE THREAD

**Issue by ridaKourchal** [quackes/webpack-encoding-plugin#1]
var EncodingPlugin = require('webpack-encoding-plugin');
.
,
    new encodingPlugin('utf8')
]
after run 
ReferenceError: encodingPlugin is not defined
    at Object.<anonymous> (D:\Projects\InventoryManagement\UIs\Jard.Web\webpack.config.js:122:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (D:\Projects\InventoryManagement\UIs\Jard.Web\node_modules\webpack\bin\convert-argv.js:80:13)
    at Object.<anonymous> (D:\Projects\InventoryManagement\UIs\Jard.Web\node_modules\webpack\bin\webpack.js:39:40)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
Process terminated with code 1.

**Comment by quackes** [comment]
use 
new EncodingPlugin('utf8')

since you use uppercase in the require assignment

btw. for utf-8 its not worth using this plugin since webpack used utf-8 by default (which is why i created the plugin)

**Comment by ridaKourchal** [comment]
it works  after compile but special characters (é, à, ..) not display ! 
Ex:
é => ? can you help please ?

thanks advanced

**Comment by quackes** [comment]
like i said.. try it without the plugin, because webpack uses utf-8 anyway..

**Comment by ridaKourchal** [comment]
i already try it but the problem special characters (é, à, ..) appear. can you give me the solution of this problem ? thanks

**Comment by quackes** [comment]
if your special chars do not render correct in utf-8 with or without plugin, maybe your sourcecode files are not encoded in utf-8.

or you could try using the plugin with a different encoding (depending on the encoding your page renders in the browser)

i created the plugin for a project that specified another encoding in html which i could not change. its controlling the output encoding, and is not meant to handle sourcecode encoding. i dont know if webpack can handle sourcecode files in other encodings than utf-8.

**Comment by ridaKourchal** [comment]
With Angular 2 , Asp.net Core 1.0
I use ISO-8859-1 instead of utf-8, i put ISO-8859-1 in my index and  new EncodingPlugin('ISO-8859-1')  in webpack.config, and i try to run webpack. after that the problem not fixed 
any idea

**Comment by quackes** [comment]
other than checking the sourcecode encoding(which should be utf-8), no.
